#%RAML 1.0 NamedExample
{
    "productDetails": [
        {
            "productId": "1",
            "productName": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
        "productPrice": 109.95,
        "productDesc": "string",
            "productCatgry": "men's clothing",
            "productImg": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
            "productRating": {
                "productRating": 3.9,
                "productCount": 120
            }
        },
        {
            "productId": "2",
            "productName": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
        "productPrice": 109.95,
        "productDesc": "string",
            "productCatgry": "men's clothing",
            "productImg": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
            "productRating": {
                "productRating": 3.9,
                "productCount": 120
            }
        },
        {
            "productId": "3",
            "productName": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
        "productPrice": 109.95,
        "productDesc": "string",
            "productCatgry": "men's clothing",
            "productImg": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
            "productRating": {
                "productRating": 3.9,
                "productCount": 120
            }
        }
    ]
}