{
  "headers": {
    "tranid": "12345",
    "source": "Internal",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.39.0",
    "accept": "*/*",
    "postman-token": "14a9c459-ef5e-4a91-9670-76c5e3d9b992",
    "host": "localhost:8091",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "206"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/product",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/product",
  "listenerPath": "/api/*",
  "relativePath": "/api/product",
  "localAddress": "/127.0.0.1:8091",
  "uriParams": {},
  "rawRequestUri": "/api/product",
  "rawRequestPath": "/api/product",
  "remoteAddress": "/127.0.0.1:56340",
  "requestPath": "/api/product"
}